### ISSUE TITLE
Old projects do not get deleted

### ISSUE THREAD

**Issue by hansteg** [godbout/alfred-time#24]
Hi,

I can't get old Toggl projects to disappear, and the list becomes unwieldy.
1) I synced repeatedly, and they are all deleted (not archived) on Toggl.
2) I reinstalled the workflow several times, and deleted all files in _application support_ or other places that seem to have something to do with this workflow. I did NOT find any cache that has a list of these projects in the clear, though.

Let me know what I can do, this workflow is excellent!

Hans

**Comment by godbout** [comment]
Hello!

Glad that you find the workflow helpful. I'll have a look at what's going on.

**Comment by godbout** [comment]
I can reproduce. Will work on a fix. Thanks for reporting!

**Comment by godbout** [comment]
Solved in 965c7e0ca6f85f94ed36be5b23156836d8e483c3. Getting some more updates done and solving an issue with tags and I'll release a new downloadable version. Will let you know.

**Comment by godbout** [comment]
Available here: https://github.com/godbout/alfred-time/releases/tag/v0.1.3

**Comment by hansteg** [comment]
Ha! Great, thanks!!

On 7 Jan 2019, at 7:52, Guill Lo wrote:

> Available here: https://github.com/godbout/alfred-time/releases/tag/v0.1.3
>
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/godbout/alfred-time/issues/24#issuecomment-451925461




All the best, Hans
_____________________________________
HANS TAMMEN

http://www.tammen.org

**Comment by godbout** [comment]
@hansteg there's a new new release, sorry 😅️ you might not need it, it's just to handle first time users a bit better if they set up wrong credentials.

**Comment by hansteg** [comment]
Got it!
