### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by bryanvlierop** [godbout/alfred-time#27]
Can you update the readme file? I don't know how to set up the toggl timer, since the config file is gone.

**Comment by godbout** [comment]
Hey, yes it’s being planned for the coming days. The README is for versions before 2.0.0. Or you can use a previous version, or, well, setting up with v2 should be pretty straightforward, no?

**Comment by bryanvlierop** [comment]
You mention that you can setup through the alfred menus, but I don't understand

**Comment by godbout** [comment]
Depends on which version you use. In 2.0.0, when you type ‘time’ there’s an option to set up the workflow. All is there.

**Comment by bryanvlierop** [comment]
If I enter 'ti' and press enter on: Time, keep tying...
It keeps Alfred open, and wants me to enter an argument, but only shows me the option to search google.

https://imgur.com/Sz7MW3s

I'm using v2.0.0

**Comment by godbout** [comment]
Well, I guess a version 2.0.1 is gonna be needed 😅️

Can you take a screenshot or copy/paste what is shown in the debugger? Thanks!

**Comment by godbout** [comment]
btw, you're using Alfred 4 right?

**Comment by bryanvlierop** [comment]
```
[10:43:02.741] Logging Started...
[10:43:06.139] Time[Script Filter] Queuing argument ''
[10:43:06.395] Time[Script Filter] Script with argument '' finished
[10:43:06.399] ERROR: Time[Script Filter] Code 255: Warning: require(/Users/bryanvanlierop/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3F48B397-C579-4DB2-AE24-A8AC1F18298E/src/../vendor/autoload.php): failed to open stream: No such file or directory in /Users/bryanvanlierop/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3F48B397-C579-4DB2-AE24-A8AC1F18298E/src/app.php on line 3

Fatal error: require(): Failed opening required '/Users/bryanvanlierop/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3F48B397-C579-4DB2-AE24-A8AC1F18298E/src/../vendor/autoload.php' (include_path='.:') in /Users/bryanvanlierop/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3F48B397-C579-4DB2-AE24-A8AC1F18298E/src/app.php on line 3
[10:43:06.400] ERROR: Time[Script Filter] JSON error: JSON text did not start with array or object and option to allow fragments not set. in JSON:
Warning: require(/Users/bryanvanlierop/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3F48B397-C579-4DB2-AE24-A8AC1F18298E/src/../vendor/autoload.php): failed to open stream: No such file or directory in /Users/bryanvanlierop/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3F48B397-C579-4DB2-AE24-A8AC1F18298E/src/app.php on line 3

Fatal error: require(): Failed opening required '/Users/bryanvanlierop/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3F48B397-C579-4DB2-AE24-A8AC1F18298E/src/../vendor/autoload.php' (include_path='.:') in /Users/bryanvanlierop/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3F48B397-C579-4DB2-AE24-A8AC1F18298E/src/app.php on line 3
```

I'm using Alfred Time v2.0.0
I'm using Alfred v4.0.1 b1078

**Comment by godbout** [comment]
Yes, indeed, some library files are missing. I will correct that and tag a new version. Thanks!

**Comment by godbout** [comment]
Solved the packaging issue. Can you try this release? https://github.com/godbout/alfred-time/releases/tag/2.0.1

**Comment by bryanvlierop** [comment]
Yeah it works!, I'm just wondering if I can move this workflow into my own workflow. I am trying to make an environment launcher and for a specific environment I need to set a toggl timer.
