### ISSUE TITLE
Possible integration with Clockify?

### ISSUE THREAD

**Issue by Pawel-Dymek** [godbout/alfred-time#28]
First of all I'd like to thank you for your awesome work, your project is great and I really appreciate all the effort you've putted there <3

I only wanted to ask have you considered adding an integration with [clockify.me](https://clockify.me/) ?
I'm asking, because it's a really great alternative for other time tracking tools and it has a very competitive pricing :P

**Comment by godbout** [comment]
hey. looks pretty nice. quite busy though. do they have a nice API? if yes, might add in the future. thanks!

**Comment by Pawel-Dymek** [comment]
imho they API is really nice and neatly documented
here, take a look - https://clockify.me/developers-api

Have a good day and thanks for the response :)

PS.: I guess that's all in this topic, right? I'll go ahead and close this github issue in order to not clutter the issues tab

**Comment by godbout** [comment]
seems nice yeah. might have a look. i put that back in open, to keep it in mind. thanks!

**Comment by godbout** [comment]
gonna start having a look this week.

**Comment by godbout** [comment]
https://github.com/godbout/alfred-time/pull/30

**Comment by Pawel-Dymek** [comment]
oh god, you are awesome :D

**Comment by godbout** [comment]
yes.

**Comment by godbout** [comment]
https://github.com/godbout/alfred-time/releases/tag/4.0.0

enjoy!

i'm gonna close that one. if you're having any issue please open another issue. thanks!

**Comment by Pawel-Dymek** [comment]
hi, sorry, it's me again :P 
First of all, new release is working almost perfectly for me and I'm really grateful for it!

I have only one issue that not all of my 74 projects are on the list. Alfred is listing exactly 50 records (and ofc I've tried typing the name of the project as well :P )
