### ISSUE TITLE
3.0 Downloadable

### ISSUE THREAD

**Issue by 42pe** [godbout/alfred-time#29]
Hi!

I think the release for 3.0 is missing the actual workflow file, in only shows the source code.

And awesome work on the plugin btw!!!

**Comment by godbout** [comment]
🤦🏻‍♂️️

good catch. thanks!

will add it today and let you know.

**Comment by godbout** [comment]
added: https://github.com/godbout/alfred-time/releases/tag/3.0.0

let me know if you have any issue. also, the Workflow doesn't do much yet, although it fulfill my needs. let me know if there's something that you'd like to be able to do with it.
