### ISSUE TITLE
Clockify - not all projects are listed

### ISSUE THREAD

**Issue by Pawel-Dymek** [godbout/alfred-time#32]
hi, sorry, it's me again :P
First of all, new release is working almost perfectly for me and I'm really grateful for it!

I have only one issue that not all of my 74 projects are on the list. Alfred is listing exactly 50 records (and ofc I've tried typing the name of the project as well :P )

PS.: I've deleted my commend below the last issue, because I've noticed that you told me to create a new issue, so there it is

**Comment by godbout** [comment]
hey! yes, i see that by default the Clockify API limits to 50 records. will change this to a hundred. but if you get more than a hundred projects, i would recommend you... to take a rest 😂️😂️😂️

glad the workflow helps. thanks for the report.

**Comment by Pawel-Dymek** [comment]
That's fair enough and thank you 😂️

**Comment by godbout** [comment]
added in 353bbdbff39df5424be3b4f1ed0aca9385cbb7d3.

i've pushed to 148 projects, so that you can double your productivity.

**Comment by godbout** [comment]
the release files should be avail in an hour or two 👍🏼️

**Comment by godbout** [comment]
ok so the release process is a bit weird for Alfred Workflows. even if all the tests are passing i might still manually fuck up when exporting (even more after a glass of Glenfiddich 15). so, can you have a look if it works well for you: https://github.com/godbout/alfred-time/releases/tag/4.1.0

thanks. if it works then i'll publish to Packal.

**Comment by godbout** [comment]
4.2.0 published on Packal.
