### ISSUE TITLE
Spelling mistake in Alfred workflow

### ISSUE THREAD

**Issue by sortofworks** [godbout/alfred-time#35]
There's a small spelling mistake of 'typing' in the Alfred workflow version 4.1.0.

![Alfred](https://user-images.githubusercontent.com/5196997/90161766-e92a0e80-dd93-11ea-926e-6edf8da3f9e1.jpg)
![Workflow setting](https://user-images.githubusercontent.com/5196997/90161844-0a8afa80-dd94-11ea-8fbd-396f216b2054.jpg)

**Comment by godbout** [comment]
trying to find a way to pretend it's done on purpose but tough one 🤔️😂️

thanks! will patch soon.

**Comment by godbout** [comment]
closed in 4.2.0.

**Comment by godbout** [comment]
https://github.com/godbout/alfred-time/releases/tag/4.2.0

**Comment by sortofworks** [comment]
Hi, the typo still seems to be present in https://github.com/godbout/alfred-time/releases/tag/4.2.0 😄
