### ISSUE TITLE
Toggl API changing

### ISSUE THREAD

**Issue by nathansnelgrove** [godbout/alfred-time#40]
I got an email from Toggl this morning about their API changing. In case this workflow needs to be updated, I thought I would share the email here. 

> We are reaching out because we detected API usage coming from your Toggl Track account using the www.toggl.com(or toggl.com) domain. 
>
> After last year's rebranding, we released api.track.toggl.com as our new domain for API usage. These changes were communicated via newsletter and the following blog post. The API Docs were also updated to reflect the domain changes. 
>
> We want to inform you that the usage of www.toggl.com(or toggl.com) domain for the API will be dropped after 'June 30th 2021'.
> 
> We encourage you to perform the switch to api.track.toggl.com as soon as possible in order to prevent disruption. 

Thank you for looking into this!

**Comment by godbout** [comment]
hey! yes. got the email today too, using Alfred Time every day 😃️

gonna update soon. thanks for taking the time to report!

**Comment by nathansnelgrove** [comment]
I thought you might have received it, but wasn't sure if you'd primarily be using Toggl or Harvest. Thought I'd report in case. Thanks so much for your time on this project; I use it many times every day and it's a lifesaver.

**Comment by godbout** [comment]
no worries. my pleasure. yeah i was using both Harvest and Toggl when i built the first version, Toggl to track and Harvest for the invoices. but ultimately i built my own invoicing system. still using Toggl for tracking daily. other services were added because some users requested.

glad it makes your day a little bit smoother! goal achieved.

**Comment by godbout** [comment]
updated: https://github.com/godbout/alfred-time/releases/tag/4.2.1

**Comment by godbout** [comment]
planning to support PHP8 soon (https://github.com/godbout/alfred-time/issues/42)
