### ISSUE TITLE
Doesn't work in macOS Monterey

### ISSUE THREAD

**Issue by nathansnelgrove** [godbout/alfred-time#46]
Hey! Wondering if you have upgraded to Monterey yet? The Time shortcut doesn't work for me, unfortunately — not sure what the problem is. I thought maybe it was a PHP compatibility problem, but I've got php 7.3.1 installed on my Mac, so that's not it.

Any thoughts?

**Comment by godbout** [comment]
good catch. installed yesterday. i can confirm yeah. Monterey stopped embedding PHP, which the Workflow (and most of the ones built in PHP) uses.

for the time being, you can edit the Workflow and point PHP to its `homebrew` or whatever install path you use.

![Alfred_Preferences](https://user-images.githubusercontent.com/121373/139092970-fc52b176-dfb5-460d-a81b-50c7cc4ed6f4.jpg)

**Comment by godbout** [comment]
i'll see what i can do in the following days. but it may be tricky. already `homebrew` uses different locations whether you're on an Intel or a Apple Silicon Mac :zzz:

**Comment by nathansnelgrove** [comment]
Man, that's a sucky problem to work through as a developer. Thanks man, much appreciated. I'll point to the Brew path I use and I guess I'll go from there! Best of luck with this.

**Comment by godbout** [comment]
for own reference: https://www.alfredapp.com/blog/releases/alfred-4-6-ready-for-macos-monterey/

**Comment by godbout** [comment]
update incoming 🚀️🚀️🚀️

PHP8, Monterey.

**Comment by nathansnelgrove** [comment]
This is super exciting! I can abandon my terribly hacky Keyboard Maestro shortcut! Thanks.

**Comment by godbout** [comment]
that sounds like a very terrible hack yes.

**Comment by godbout** [comment]
i haven't touched Alfred Workflows or PHP for a whole so maybe i fucked every up. let me know if it's the case. the update should be out in ten min. will ping. you.

**Comment by godbout** [comment]
https://github.com/godbout/alfred-time/releases/tag/4.3.0

man i hope it works. else i'll stop being a developer forever (but just for a week).

**Comment by nathansnelgrove** [comment]
I am so grateful for your work on this. Unfortunately, I can't seem to trigger the "time" command. Tried uninstalling and reinstalling. Not sure what I've done, but it's probably something dumb.

**Comment by nathansnelgrove** [comment]
FWIW, I tried updating PHP via Brew to PHP 8.1.0, and still can't run the Time command from Alfred. Again, it's probably something local to my machine. I probably need to reboot or something weird like that. Apologies if it's that easy and I'm about to send you down a rabbit hole.

**Comment by godbout** [comment]
currently up to PHP8.0, not 8.1. Alfred Time uses some other packages that are not updated for 8.1 yet. so it's 7.4 or 8.0.

**Comment by godbout** [comment]
yeah, that's gonna be the issue with PHP unfortunately. you gonna the right version to run that shit ☹️

**Comment by nathansnelgrove** [comment]
*Of course!* Fixed. Installed PHP 8 via Brew, and copied and pasted this script in place yours:

`export PATH="/usr/local/opt/php@8.0/bin:${PATH}"`

Everything works now. Sir, I owe you a beer. Several beers. Or coffee, or money, or whatever your preference is really. Thanks for your work on this. It makes my day substantially easier.

**Comment by godbout** [comment]
well the fact that you're having a better thanks to what i'm doing is all i need 🙂️ just kidding. yeah a couple of beers would be nice 😂️😂️😂️

alright, enjoy!
and thanks for having taken the time to report. will close that one. see you at the next.

**Comment by nathansnelgrove** [comment]
If you're ever in Toronto or the Hamilton area of Canada, give me a holler and I'll get you those beers. Cheers!

**Comment by godbout** [comment]
i didn't know Canadians could use the software. i'll have to update the license.

**Comment by domwass** [comment]
Thanks from Germany, guys – due to your guidance I managed to get Time running under Monterey again!

**Comment by godbout** [comment]
great! the pleasure is @nathansnelgrove's. danke for the coffee. tomorrow's is on you.
